"""Render the paste-ready abuse report from a scored candidate.

This is the project's deliverable. The report reads as factual, evidence-led
observation — not an accusation. It always states that any binary was inspected
by parsing bytes and never executed, and always carries an allowlist caveat so a
wrongly-flagged legitimate fork/mirror/translation is easy to suppress.
"""

from __future__ import annotations

from dataclasses import dataclass

from .config import Config
from .models import Project, ScoredCandidate

# Pure-text guarantee mandated by the project's hard rules.
NEVER_EXECUTED_STATEMENT = (
    "Any binary referenced here was inspected by parsing its bytes "
    "(e.g. PE version resources); it was **never executed**."
)

# Suggested categories to select on GitHub's content-report form. The maintainer,
# as the rights holder, files the report — this just points at the right options.
ABUSE_CATEGORIES = (
    "It infringes my copyright or trademark rights",
    "It impersonates me or my project (passing itself off as the original)",
)


@dataclass(frozen=True)
class RenderedReport:
    title: str
    body: str


def dedupe_marker(candidate) -> str:
    """Hidden HTML comment used to find an existing issue for this candidate.

    Lowercased so it is stable across runs regardless of owner/name casing.
    """
    return f"<!-- rim:{candidate.full_name.lower()} -->"


def _observations(scored: ScoredCandidate) -> str:
    lines = []
    for s in scored.triggered_signals:
        detail = s.detail or s.label
        lines.append(f"- **{s.label}** — {detail}")
    if not lines:
        return "- (no individual signals triggered)"
    return "\n".join(lines)


def _pe_section(scored: ScoredCandidate) -> str:
    pe = scored.pe_metadata
    if pe is None or not pe.parse_ok:
        return ""
    fields = [
        ("ProductName", pe.product_name),
        ("CompanyName", pe.company_name),
        ("OriginalFilename", pe.original_filename),
        ("FileDescription", pe.file_description),
    ]
    rows = [f"- {label}: `{value}`" for label, value in fields if value]
    if not rows:
        return ""
    return (
        "### Binary version-resource fields\n\n"
        "The release binary's embedded version resources name an unrelated "
        "product:\n\n" + "\n".join(rows) + "\n"
    )


def render(scored: ScoredCandidate, project: Project, config: Config) -> RenderedReport:
    """Build the issue title + Markdown body for a scored candidate."""
    cand = scored.candidate
    title = f"Possible impersonation of {project.name}: {cand.full_name} [{scored.tier.name}]"

    categories = "\n".join(f"- {c}" for c in ABUSE_CATEGORIES)
    pe_section = _pe_section(scored)

    body = f"""{dedupe_marker(cand)}
## Suspected impersonation report — {scored.tier.name} confidence

This is an automated, evidence-led observation generated by
[repo-impersonation-monitor](https://github.com/{config.project_repo}). It is a
draft for the maintainer to review and, if appropriate, file. Nothing has been
reported automatically.

| | |
|---|---|
| **Real project** | {project.name} — {config.real_html_url} |
| **Suspected impersonator** | {cand.full_name} — {cand.html_url} |
| **Clone URL** | `{cand.clone_url}` |
| **Discovered via** | {cand.discovered_via} |
| **Candidate created** | {cand.created_at:%Y-%m-%d} |
| **Is a fork** | {"yes" if cand.is_fork else "no"} |
| **Confidence tier** | {scored.tier.name} (score {scored.score:.2f}) |

### Observations

{_observations(scored)}

{pe_section}
### Binary handling

{NEVER_EXECUTED_STATEMENT}

### Suggested report categories

When filing via GitHub's content-report form, the categories that typically
apply:

{categories}

### If this is a false positive

If {cand.full_name} is a legitimate fork, mirror, or translation, add it to this
Action's `allowlist` input so it is not surfaced again:

```
{cand.full_name}
```
"""
    return RenderedReport(title=title, body=body)
