"""Tests for the PE version-resource reader.

Uses real PE fixtures (generated by tests/fixtures/_generate_pe_fixtures.py) so
the test exercises actual pefile parsing, not mocks. Also statically enforces
the never-execute contract.
"""

from pathlib import Path

import pytest

from repo_impersonation_monitor import pe
from repo_impersonation_monitor.pe import is_pe_asset, read_version_resources

FIXTURES = Path(__file__).parent / "fixtures"


def read_fixture(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


# --- real-PE parsing ------------------------------------------------------

def test_reads_mismatch_fixture_fields():
    meta = read_version_resources(read_fixture("pe_mismatch.exe"))
    assert meta.parse_ok is True
    assert meta.product_name == "Janus Key"
    assert meta.company_name == "Duality Solutions"
    assert meta.original_filename == "JanusKey-Setup.exe"
    assert meta.file_description == "Janus Key Licensed Installer"


def test_raw_string_table_captured():
    meta = read_version_resources(read_fixture("pe_mismatch.exe"))
    assert meta.raw_string_table.get("FileVersion") == "1.0.0.0"
    assert meta.raw_string_table.get("ProductName") == "Janus Key"


def test_reads_matching_fixture_fields():
    meta = read_version_resources(read_fixture("pe_match.exe"))
    assert meta.parse_ok is True
    assert meta.product_name == "MyProject"
    assert meta.company_name == "MyProject Authors"


# --- graceful failure on hostile/garbage bytes ---------------------------

def test_garbage_bytes_parse_not_ok():
    meta = read_version_resources(b"this is not a PE file at all")
    assert meta.parse_ok is False
    assert meta.parse_error
    assert meta.product_name is None


def test_empty_bytes_parse_not_ok():
    meta = read_version_resources(b"")
    assert meta.parse_ok is False


def test_truncated_pe_header_parse_not_ok():
    # Valid MZ magic but truncated — must not raise.
    meta = read_version_resources(b"MZ" + b"\x00" * 10)
    assert meta.parse_ok is False


def test_pe_without_version_resource_parse_ok_but_empty():
    # A PE that parses but has no version resource: parse_ok True, fields None.
    # Build one by stripping nothing special — reuse a valid PE and assert the
    # reader does not invent fields. (mismatch fixture HAS fields, so we only
    # assert the no-crash contract on a minimal valid-ish header here.)
    meta = read_version_resources(b"MZ" + b"\x00" * 200)
    assert meta.parse_ok is False  # too minimal to be a real PE


# --- never-execute contract ----------------------------------------------

def test_pe_module_never_executes_code():
    """Static guard: the module must not import or call process/exec APIs."""
    source = Path(pe.__file__).read_text()
    for forbidden in ("subprocess", "os.system", "os.popen", "exec(", "eval(", "ctypes"):
        assert forbidden not in source, f"pe.py must not reference {forbidden!r}"


def test_read_takes_bytes_not_path():
    # Passing a path string must not cause a file to be opened/executed; it is
    # just treated as (invalid) bytes once encoded. We assert it does not raise.
    meta = read_version_resources(b"/bin/sh")
    assert meta.parse_ok is False


# --- asset gating ---------------------------------------------------------

@pytest.mark.parametrize("name,expected", [
    ("setup.exe", True),
    ("lib.dll", True),
    ("TOOL.EXE", True),
    ("archive.7z", False),
    ("source.zip", False),
    ("installer.msi", False),
    ("readme.txt", False),
    ("", False),
])
def test_is_pe_asset_by_extension(name, expected):
    assert is_pe_asset(name) is expected


# --- helper branch coverage ----------------------------------------------

def test_decode_handles_non_bytes_value():
    assert pe._decode("already-text") == "already-text"
    assert pe._decode(b"bytes-value") == "bytes-value"


def test_collect_string_table_returns_empty_without_fileinfo():
    class _NoFileInfo:
        pass

    assert pe._collect_string_table(_NoFileInfo()) == {}
